package global

const (
	WINDOW_WIDTH  = 1200
	WINDOW_HEIGHT = 800
	WINDOW_NAME   = "grit"

	TARGET_RENDER_FPS = 240

	PIXEL_SIZE  = 2
	GRID_WIDTH  = WINDOW_WIDTH / PIXEL_SIZE
	GRID_HEIGHT = WINDOW_HEIGHT / PIXEL_SIZE

	// higher the priority the more it will rise to the top like in rise of kingdoms
	EDGE_PRIORITY  = 1
	BRICK_PRIORITY = 2
	SAND_PRIORITY  = 2
	WATER_PRIORITY = 3
	EMPTY_PRIORITY = 4

// BORDER_WIDTH  = (GRID_WIDTH*PIXEL_SIZE - WINDOW_WIDTH) / 2
// BORDER_HEIGHT = (GRID_HEIGHT*PIXEL_SIZE - WINDOW_WIDTH) / 2
)
